import { describe, expect, it } from 'vitest';
import { carriesAttribution } from '@/internal/hooks/carries-attribution';

// Built from parts so the fixtures do not trip an attribution guard on this very file.
const TRAILER = ['Co', 'Authored', 'By'].join('-');

describe('carriesAttribution', () => {
  it.each([
    `${TRAILER}: Claude <noreply@anthropic.com>`,
    `${TRAILER.toLowerCase()}: someone@anthropic.com`,
    `${['Claude', 'Session'].join('-')}: https://x`,
    'Generated by Claude',
    'generated with [Claude Code](https://claude.com/claude-code)',
    `a ${String.fromCodePoint(0x1f916)} badge`,
  ])('finds %s', (text) => {
    expect(carriesAttribution(text)).toBe(true);
  });

  it.each([`${TRAILER}: Ada <ada@example.com>`, 'Claude wrote a poem', 'generated with care'])(
    'passes %s',
    (text) => {
      expect(carriesAttribution(text)).toBe(false);
    },
  );
});
